# Generated by Django 6.0.1 on 2026-01-23 03:04

from django.db import migrations


def add_default_categories(apps, schema_editor):
    Category = apps.get_model('auctions', 'Category')
    categories = [
        ('Electronics', 'electronics'),
        ('Fashion', 'fashion'),
        ('Home & Garden', 'home-garden'),
        ('Sports & Outdoors', 'sports-outdoors'),
        ('Toys & Games', 'toys-games'),
        ('Books', 'books'),
        ('Music', 'music'),
        ('Art & Collectibles', 'art-collectibles'),
    ]
    for name, slug in categories:
        Category.objects.create(name=name, slug=slug)


def remove_default_categories(apps, schema_editor):
    Category = apps.get_model('auctions', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_comment_bid'),
    ]

    operations = [
        migrations.RunPython(add_default_categories, remove_default_categories),
    ]
